# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from anomaly_engine import AnomalyEngine
from anomaly_logger import AnomalyLogger
from bus_manager import BusManager
from camera_manager import CameraManager
from comparison_engine import ComparisonEngine
from config_store import ConfigStore
from copilot_agent import CopilotAgent
from custom_object_matcher import CustomObjectMatcher
from data_source_manager import DataSourceManager
from dbc_catalog_db import DbcCatalogDb
from ethernet_manager import EthernetManager
from experimental_assistant import ExperimentalAssistantService
from flask import Flask, Response, jsonify, render_template, request, send_file, send_from_directory
from flask_socketio import SocketIO
from gateway_mirror import build_mirror_mode_write_request, default_mirror_definition
from llm_singleflight import LLM_SINGLEFLIGHT_LOCK
from logger import BusLogger
from mf4_replay import MF4ReplayService
from pdx_parser import PdxAnalyzeOptions, analyze_pdx, build_did_index_from_pdx, build_dtc_index_from_pdx, extract_gateway_mirror_definition_from_pdx
from rule_suggester import suggest_rules_from_session_csv
from shared_frame_buffer import SharedFrameBuffer
from typing import Any, Dict
from vag_scanner import VAGScannerService
from video_recorder import VideoRecorder
from video_streamer import MJPEGStreamer
from violation_logger import ViolationLogger
import canlib.canlib
import io
import json
import os
import re
import socket
import struct
import subprocess
import sys
import threading
import time
import uuid
import zipfile

class MockCanLib:
_copilot_rule_drafts: Dict[str, Dict[str, Any]] = {}
def _copilot_prune_rule_drafts() -> None:
    ...

def _copilot_parse_simple_op(m: str) -> str | None:
    ...

def _copilot_parse_first_number(m: str) -> float | None:
    ...

def _copilot_rule_metric(m: str) -> str | None:
    ...

def _copilot_split_composite_clauses(user_msg: str) -> tuple[list[str], str] | tuple[None, None]:
    ...

def _copilot_parse_clause(clause: str) -> Dict[str, Any] | None:
    ...

def _copilot_pick_signal_for_metric(dbc_search: Dict[str, Any] | None, metric: str) -> Dict[str, Any] | None:
    ...

def _copilot_metric_terms(metric: str) -> str:
    ...

def _copilot_build_metric_dbc_search(snapshot: Dict[str, Any] | None, metric: str) -> Dict[str, Any]:
    ...

def _copilot_pick_source_id(snapshot: Dict[str, Any] | None) -> str | None:
    ...

def _copilot_is_rule_wizard_question(user_msg: str) -> bool:
    ...

def _copilot_build_rule_examples_answer() -> str:
    ...

def _copilot_try_handle_rule_wizard(msg: str, snapshot: Dict[str, Any], chat_ctx: Dict[str, Any]) -> str | None:
    ...

def _session_meta_filename(base: str) -> str:
    ...

def _session_base_from_pathlike(pathlike: Any) -> str | None:
    ...

def _find_session_meta_path(base: str) -> str | None:
    ...

def _read_session_meta(base: str) -> dict:
    ...

def _write_session_meta(base: str, patch: dict) -> None:
    ...

def _append_session_event(base: str, name: str) -> None:
    ...

def _no_cache_static_assets(response: Any) -> Any:
    ...

LOG_FOLDER = DEFAULT_LOG_FOLDER
def _safe_basename(name: str) -> str | None:
    ...

def _pdx_path_for(filename: str) -> str | None:
    ...

def _pdx_report_path_for(filename: str) -> str | None:
    ...

def _get_active_pdx_path() -> str | None:
    ...

def _ensure_writable_dir(path: str) -> str:
    ...

def _resolve_storage_output_dir(cfg: Any) -> str:
    ...

def _iter_log_folders() -> Any:
    ...

def _find_log_file(filename: str) -> Any:
    ...

def _bootstrap_config_from_example_if_missing() -> None:
    ...

sm = ''
es0 = _saved_config.get('eth_settings') if isinstance(_saved_config.get('eth_settings'), dict) else {}
iface0 = ''
inferred = 'simulation' if iface0 == 'lo' else 'real'
_video_recording_enabled = True
def _ensure_eth_running_for_logging() -> None:
    ...

def _log_event(event_name: str, details: dict) -> None:
    ...

def _parse_formats(val: str) -> Any:
    ...

_motion_trigger_enabled = str(os.getenv('CAM_MOTION_TRIGGER', '0')).strip().lower() in {'1', 'true', 'yes', 'on'}
_yolo_trigger_armed = str(os.getenv('CAM_YOLO_TRIGGER', '0')).strip().lower() in {'1', 'true', 'yes', 'on'}
_yolo_trigger_classes = [c.strip() for c in (os.getenv('CAM_YOLO_CLASSES', '') or '').split(',') if c.strip()]
_custom_trigger_armed = str(os.getenv('CAM_CUSTOM_TRIGGER', '0')).strip().lower() in {'1', 'true', 'yes', 'on'}
_custom_trigger_objects = [c.strip() for c in (os.getenv('CAM_CUSTOM_OBJECTS', '') or '').split(',') if c.strip()]
_trigger_rules = {'enabled': bool(_saved_config.get('trigger_rules', {}).get('enabled', False)), 'mode': str(_saved_config.get('trigger_rules', {}).get('mode', 'any') or 'any'), 'sources': list(_saved_config.get('trigger_rules', {}).get('sources', ['yolo'])), 'window_s': float(_saved_config.get('trigger_rules', {}).get('window_s', 2.0) or 2.0), 'cooldown_s': float(_saved_config.get('trigger_rules', {}).get('cooldown_s', 2.0) or 2.0), 'formats': list(_saved_config.get('trigger_rules', {}).get('formats', [])), 'video_preroll_s': float(_saved_config.get('trigger_rules', {}).get('video_preroll_s', 0.0) or 0.0), 'auto_stop_enabled': bool(_saved_config.get('trigger_rules', {}).get('auto_stop_enabled', False)), 'auto_stop_s': float(_saved_config.get('trigger_rules', {}).get('auto_stop_s', 0.0) or 0.0)}
_trigger_state = {'last': {}, 'last_start_s': 0.0}
_last_trigger_event_s = 0.0
_log_started_by_trigger = False
_log_started_source = None
_trigger_activity_s = {'yolo': 0.0, 'motion': 0.0, 'custom': 0.0, 'can': 0.0, 'eth': 0.0}
_suppress_until_clear = {'yolo': False, 'motion': False, 'custom': False, 'can': False, 'eth': False}
_manual_stop_latch = {'yolo': False, 'motion': False, 'custom': False, 'can': False, 'eth': False}
_yolo_prev_present_app = False
def _reset_yolo_edge_state() -> None:
    ...

def _to_number(v: Any) -> Any:
    ...

def _eval_condition(actual: Any, op: str, expected_raw: Any) -> bool:
    ...

_restore_armed_on_boot = str(os.getenv('KBSM_RESTORE_ARMED', '')).strip().lower() in {'1', 'true', 'yes', 'on'}
_can_trigger_cfg = {'armed': bool((_saved_config.get('can_trigger') or {}).get('armed', False)) if _restore_armed_on_boot else False, 'channel_id': int((_saved_config.get('can_trigger') or {}).get('channel_id', 0) or 0), 'dbc_name': str((_saved_config.get('can_trigger') or {}).get('dbc_name', '') or ''), 'message': str((_saved_config.get('can_trigger') or {}).get('message', '') or ''), 'signal': str((_saved_config.get('can_trigger') or {}).get('signal', '') or ''), 'start_op': str((_saved_config.get('can_trigger') or {}).get('start_op', 'eq') or 'eq'), 'start_value': (_saved_config.get('can_trigger') or {}).get('start_value', 1), 'auto_stop_enabled': bool((_saved_config.get('can_trigger') or {}).get('auto_stop_enabled', False)), 'no_message_stop_s': float((_saved_config.get('can_trigger') or {}).get('no_message_stop_s', 2.0) or 2.0), 'stop_op': str((_saved_config.get('can_trigger') or {}).get('stop_op', 'eq') or 'eq'), 'stop_value': (_saved_config.get('can_trigger') or {}).get('stop_value', 0), 'formats': list((_saved_config.get('can_trigger') or {}).get('formats', []))}
_can_trigger_state = {'active': False, 'last_match_ms': 0, 'last_seen_ms': 0}
_eth_trigger_cfg = {'armed': bool((_saved_config.get('eth_trigger') or {}).get('armed', False)) if _restore_armed_on_boot else False, 'formats': list((_saved_config.get('eth_trigger') or {}).get('formats', [])) or ['csv', 'txt'], 'cooldown_s': float((_saved_config.get('eth_trigger') or {}).get('cooldown_s', 2.0) or 2.0)}
_eth_trigger_state = {'last_start_s': 0.0}
def _start_logging_async(formats: Any) -> Any:
    ...

def _stop_logging_async() -> Any:
    ...

def _on_can_frame_for_trigger(frame: dict) -> None:
    ...

def _can_trigger_watchdog_loop() -> Any:
    ...

def _apply_saved_config_defaults() -> None:
    ...

def _on_camera_trigger(details: dict) -> None:
    ...

def _on_eth_trigger(packet: dict) -> None:
    ...

def trigger_rules_config() -> Any:
    ...

def yolo_trigger_config() -> Any:
    ...

def yolo_test_once() -> Any:
    ...

def custom_trigger_config() -> Any:
    ...

def custom_objects_list() -> Any:
    ...

def custom_objects_capture() -> Any:
    ...

def custom_objects_train() -> Any:
    ...

def custom_test_once() -> Any:
    ...

cam_autostart = str(os.getenv('CAM_AUTOSTART', '0') or '0').strip().lower() in {'1', 'true', 'yes', 'on'}
cam_autostart = False
def _recording_sync_loop() -> Any:
    ...

def video_recording_config() -> Any:
    ...

def _trigger_autostop_loop() -> Any:
    ...

_init_cfg = config_store.get_config_only() or {}
_init_gm = _init_cfg.get('gateway_mirror') if isinstance(_init_cfg.get('gateway_mirror'), dict) else {}
def _log_dir_resolver() -> str:
    ...

_mirror_channel_map: Dict[int, int] = {}
def _rebuild_mirror_channel_map() -> None:
    ...

def _resolve_source_id(bus_type: str, channel_id: int) -> Any:
    ...

def _preload_dbcs_from_sources() -> None:
    ...

_copilot_snapshot_cache: Dict[str, Any] = {'ts_ms': 0, 'data': {}}
def _sentinel_env_str(name: str, default: str) -> str:
    ...

def _sentinel_env_float(name: str, default: float) -> float:
    ...

def _sentinel_env_int(name: str, default: int) -> int:
    ...

def _sentinel_system_prompt() -> str:
    ...

def _sentinel_make_agent() -> CopilotAgent:
    ...

_sentinel_llm_lock = None
_sentinel_llm_last_error: Dict[str, Any] = {'ts_ms': 0, 'error': ''}
_sentinel_llm_inflight_since_s: float = 0.0
_sentinel_llm_last_start_s: float = 0.0
_copilot_llm_lock = LLM_SINGLEFLIGHT_LOCK
_copilot_llm_cooldown_until_s: float = 0.0
_copilot_llm_last_error: Dict[str, Any] = {'ts_ms': 0, 'error': ''}
_copilot_ollama_last_stop_s: float = 0.0
_copilot_llm_inflight_since_s: float = 0.0
_copilot_llm_last_start_s: float = 0.0
_sentinel_llm_lock = _copilot_llm_lock
def _copilot_maybe_stop_ollama_model(reason: str) -> None:
    ...

def _copilot_ollama_watchdog_loop() -> None:
    ...

def _copilot_build_snapshot() -> Dict[str, Any]:
    ...

def _copilot_system_prompt() -> str:
    ...

def _copilot_build_chat_context(snapshot: Dict[str, Any]) -> Dict[str, Any]:
    ...

def _copilot_should_do_dbc_lookup(user_msg: str) -> bool:
    ...

def _copilot_extract_search_terms(user_msg: str) -> str:
    ...

def _copilot_is_signal_name_question(user_msg: str) -> bool:
    ...

def _copilot_is_ai_config_question(user_msg: str) -> bool:
    ...

def _copilot_is_violation_config_question(user_msg: str) -> bool:
    ...

def _copilot_build_violation_config_answer(snapshot: Dict[str, Any] | None) -> str:
    ...

def _copilot_faq_target(user_msg: str) -> str | None:
    ...

def _copilot_build_faq_answer(key: str, snapshot: Dict[str, Any] | None) -> str:
    ...

def _copilot_page_help_target(user_msg: str) -> str | None:
    ...

def _copilot_build_page_help_answer(page: str, snapshot: Dict[str, Any] | None) -> str:
    ...

def _copilot_build_ai_config_answer(snapshot: Dict[str, Any] | None) -> str:
    ...

def _copilot_router_decision(system: str, user_msg: str, chat_ctx: Dict[str, Any]) -> str:
    ...

def _copilot_env_float(name: str, default: float) -> float:
    ...

def _copilot_env_int(name: str, default: int) -> int:
    ...

def _copilot_build_deterministic_signal_answer(dbc_search: Dict[str, Any], user_msg: str) -> str:
    ...

def _copilot_build_dbc_search_context(snapshot: Dict[str, Any], user_msg: str) -> Dict[str, Any]:
    ...

def sources_page() -> Any:
    ...

def comparison_page() -> Any:
    ...

def violations_page() -> Any:
    ...

def ai_page() -> Any:
    ...

def copilot_page() -> Any:
    ...

def dbc_catalog_page() -> Any:
    ...

def fibex_catalog_page() -> Any:
    ...

def experimental_page() -> Any:
    ...

def timeline_page() -> Any:
    ...

def _experimental_defaults() -> dict:
    ...

def _get_experimental_settings() -> dict:
    ...

def api_experimental_settings() -> Any:
    ...

def api_experimental_status() -> Any:
    ...

def api_experimental_incidents() -> Any:
    ...

def api_experimental_incidents_clear() -> Any:
    ...

def api_experimental_simulate_mil_on() -> Any:
    ...

def api_experimental_simulate_lamp_on() -> Any:
    ...

def api_copilot_status() -> Any:
    ...

def api_copilot_snapshot() -> Any:
    ...

def api_copilot_chat() -> Any:
    ...

def api_sentinel_status() -> Any:
    ...

def api_sentinel_chat() -> Any:
    ...

def api_sentinel_test_random_dtcs() -> Any:
    ...

def api_sentinel_ingest_scan_report() -> Any:
    ...

def api_sentinel_analyze_dtcs() -> Any:
    ...

def monitor_list_dbcs() -> Any:
    ...

def _mf4_replay_saved_config() -> dict:
    ...

def _mf4_replay_sanitize_config(obj: dict) -> dict:
    ...

def mf4_replay_config() -> Any:
    ...

def mf4_replay_status() -> Any:
    ...

def mf4_replay_stop() -> Any:
    ...

def mf4_replay_start() -> Any:
    ...

def _is_local_request() -> bool:
    ...

def monitor_demo_frame() -> Any:
    ...

def monitor_demo_violation() -> Any:
    ...

def monitor_demo_anomaly() -> Any:
    ...

def ai_config() -> Any:
    ...

def ai_status() -> Any:
    ...

def ai_train_live() -> Any:
    ...

def ai_list_anomalies() -> Any:
    ...

def ai_suggest_rules() -> Any:
    ...

def ai_apply_suggestions() -> Any:
    ...

def api_sources() -> Any:
    ...

def api_source_item(source_id: str) -> Any:
    ...

def api_sources_export() -> Any:
    ...

def api_sources_import() -> Any:
    ...

def api_source_test(source_id: str) -> Any:
    ...

def api_comparison_rules() -> Any:
    ...

def api_comparison_rule_item(rule_id: str) -> Any:
    ...

def api_comparison_rules_reload() -> Any:
    ...

def api_violations_query() -> Any:
    ...

def api_violations_stats() -> Any:
    ...

def api_violations_clear() -> Any:
    ...

_dbc_describe_cache = {}
def _truthy(v: Any) -> bool:
    ...

def describe_dbc() -> Any:
    ...

def dbc_catalog() -> Any:
    ...

def api_dbc_db_list() -> Any:
    ...

def api_dbc_db_import() -> Any:
    ...

def api_dbc_db_catalog() -> Any:
    ...

def api_dbc_db_signals_for_message() -> Any:
    ...

def api_dbc_db_search_signals() -> Any:
    ...

def can_trigger_config() -> Any:
    ...

def eth_trigger_config() -> Any:
    ...

def api_config() -> Any:
    ...

def _group_sessions() -> dict:
    ...

def list_sessions() -> Any:
    ...

def session_bundle() -> Any:
    ...

def index() -> Any:
    ...

def get_interfaces() -> Any:
    ...

def get_dbcs() -> Any:
    ...

def get_fibexs() -> Any:
    ...

def get_arxmls() -> Any:
    ...

def describe_fibex() -> Any:
    ...

def list_logs() -> Any:
    ...

def api_health() -> Any:
    ...

def api_system_stats() -> Any:
    ...

def api_system_power() -> Any:
    ...

def mf4_list_files() -> Any:
    ...

def mf4_list_raw_channels() -> Any:
    ...

def mf4_info() -> Any:
    ...

def mf4_upload_file() -> Any:
    ...

def mf4_list_signals() -> Any:
    ...

def mf4_get_data() -> Any:
    ...

def _resolve_dbc_path(dbc_name: str) -> Any:
    ...

def _mf4_load_raw_table(path: str) -> Any:
    ...

def _mf4_configured_dbcs_by_channel() -> dict[int, list[str]]:
    ...

def mf4_list_decoded_signals() -> Any:
    ...

def _despike_series(t_list: list, y_list: list) -> tuple:
    ...

def mf4_get_decoded_data() -> Any:
    ...

def mf4_export_decoded_mf4() -> Any:
    ...

def mf4_decode_csv_download() -> Any:
    ...

def delete_all_logs() -> Any:
    ...

def start_scan() -> Any:
    ...

def scantools_run() -> Any:
    ...

def scantools_status() -> Any:
    ...

def scantools_live_start() -> Any:
    ...

def scantools_live_stop() -> Any:
    ...

def download_log(filename: Any) -> Any:
    ...

def delete_log(filename: Any) -> Any:
    ...

def camera_status() -> Any:
    ...

def inject_can_frame() -> Any:
    ...

def inject_can_burst() -> Any:
    ...

def bus_stats() -> Any:
    ...

def _bus_stats_loop() -> Any:
    ...

def inject_can_batch() -> Any:
    ...

def inject_can_batch_fast() -> Any:
    ...

def debug_fire_trigger() -> Any:
    ...

def debug_eth_inject() -> Any:
    ...

def camera_stream() -> Any:
    ...

def video_status() -> Any:
    ...

def video_file_stream() -> Any:
    ...

def session_manifest() -> Any:
    ...

_bus_start_in_progress = False
_bus_start_last_error = None
_bus_start_last_result = None
_bus_start_last_ts = None
def _start_bus_worker(payload: dict) -> None:
    ...

def _kickoff_bus_start_async(payload: dict) -> bool:
    ...

def start_bus() -> Any:
    ...

def stop_bus() -> Any:
    ...

def start_log() -> Any:
    ...

def acq_start() -> Any:
    ...

def log_status() -> Any:
    ...

def runtime_status() -> Any:
    ...

def stop_log() -> Any:
    ...

def acq_stop() -> Any:
    ...

def upload_dbc() -> Any:
    ...

def upload_fibex() -> Any:
    ...

def upload_arxml() -> Any:
    ...

def arxml_get_catalog() -> Any:
    ...

def arxml_list_files() -> Any:
    ...

def arxml_delete_file() -> Any:
    ...

def arxml_reload_catalog() -> Any:
    ...

def import_pdx_project() -> Any:
    ...

def list_pdx_projects() -> Any:
    ...

def select_pdx_project() -> Any:
    ...

def get_pdx_report() -> Any:
    ...

def _get_iface_ipv4_best_effort(ifname: str) -> str | None:
    ...

def _get_default_route_iface_best_effort() -> str | None:
    ...

def doip_config_page() -> Any:
    ...

def doip_status() -> Any:
    ...

def doip_config_api() -> Any:
    ...

def doip_discover_api() -> Any:
    ...

def start_eth() -> Any:
    ...

def stop_eth() -> Any:
    ...

def eth_status() -> Any:
    ...

def send_doip_uds() -> Any:
    ...

def gateway_mirror_definition() -> Any:
    ...

def _parse_int_maybe_hex(v: Any) -> int:
    ...

def _effective_eth_iface_from_config(cfg: Dict[str, Any]) -> str | None:
    ...

def _gateway_mirror_defaults() -> Dict[str, Any]:
    ...

def _normalize_gateway_mirror_config(raw: Any) -> Dict[str, Any]:
    ...

def _get_gateway_mirror_config() -> Dict[str, Any]:
    ...

def _resolve_mirror_did_from_active_pdx(default_did: int) -> int:
    ...

def _resolve_gateway_ip_for_mirror(cfg: Dict[str, Any]) -> str:
    ...

def _discover_gateway_mirror_target_addr() -> int:
    ...

def _load_mirror_dbcs() -> int:
    ...

def _gateway_mirror_send_from_config(enable: bool, cfg: Dict[str, Any]) -> tuple[Dict[str, Any], int]:
    ...

def gateway_mirror_discover_target_addr() -> Any:
    ...

def gateway_mirror_get_config() -> Any:
    ...

def gateway_mirror_set_config() -> Any:
    ...

def gateway_mirror_start() -> Any:
    ...

def gateway_mirror_stop() -> Any:
    ...

def gateway_mirror_enable() -> Any:
    ...

def gateway_mirror_disable() -> Any:
    ...

def eth_stats_loop() -> Any:
    ...

def _autostart_from_saved_config() -> None:
    ...

def system_set_mode() -> Any:
    ...

def _enforce_system_mode_patch() -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import flask
import flask.Flask
import flask.render_template
import flask.request
import flask.jsonify
import flask.send_from_directory
import flask.send_file
import flask.Response
import flask_socketio
import flask_socketio.SocketIO
import threading
import time
import os
import io
import re
import subprocess
import zipfile
import json
import socket
import struct
import uuid
import sys
import typing
import canlib
import canlib.canlib
import bus_manager
import ethernet_manager
import logger
import vag_scanner
import shared_frame_buffer
import camera_manager
import video_streamer
import video_recorder
import custom_object_matcher
import config_store
import pdx_parser
import data_source_manager
import violation_logger
import dbc_catalog_db
import comparison_engine
import anomaly_logger
import anomaly_engine
import rule_suggester
import mf4_replay
import copilot_agent
import experimental_assistant
import posixpath
import gateway_mirror
import llm_singleflight
import dbc_loader
import random
import html
import datetime
import werkzeug
import werkzeug.utils
import cantools
import flask.after_this_request
import tempfile
import fibex_loader
import shutil
import numpy
import asammdf
import math
import arxml_decoder
import array
import asammdf.Signal
import csv
import arxml_parser
import fcntl
import __future__
import monitor_types
import sqlite3
import xml
import xml.etree
import xml.etree.ElementTree
import dataclasses
import can_handler
import flexray_handler
import diagnostics
import collections
import collections.deque
import cv2
import ultralytics
import ultralytics.YOLO
import queue
import urllib
import urllib.error
import urllib.request
import traceback
import pyarmor_runtime_000000
import backend.dist.pyarmor_runtime_000000.pyarmor_runtime
import scapy
import scapy.all
import someip_parser
import ethernet_capture
import doip_client
import xcp_eth_client
import mf4_logger
import mf4_decoded_export
import ipaddress
import inspect
import asammdf.MDF
import collections.defaultdict
import pandas
import collections.Counter
import can
import isotp
import base64