#!/usr/bin/env bash
# install_master_turnkey.sh — provisiona un Pi 5 16 GB come MASTER COMPLETO.
#
# Eseguito UNA VOLTA su un Pi 5 nuovo, dopo `git clone -b master ... && cd repo`,
# porta il sistema da zero a stato funzionante in vettura.
#
# Fasi:
#   1. dipendenze apt
#   2. git lfs pull (scarica DBC/ARXML/FIBEX/PDX/A2L/ODX da LFS, ~480 MB)
#   3. venv Python con tutte le deps (Flask, asammdf, cantools, scapy, ecc.)
#   4. Kvaser kernel modules (se la USB Kvaser è collegata)
#   5. netplan eth0 statico (default 192.168.50.10/24)
#   6. systemd unit trc-master.service + trc-heartbeat.service (opzionale)
#   7. TRC heartbeat config (da template se non esiste)
#   8. autostart kiosk display (XDG autostart)
#   9. /etc/default/trc-master env file
#  10. (opzionale) VPN WireGuard se key file fornite
#  11. (opzionale) Hailo-8 driver se M.2 module presente
#  12. start dei servizi
#
# Uso:
#   sudo bash master_node/install/install_master_turnkey.sh
#
# Override env:
#   STATIC_IP=192.168.50.10
#   SLAVE_IP=192.168.50.20
#   TRC_SERVER_URL=http://172.30.96.143:8787
#   ENABLE_HEARTBEAT=1
#   ENABLE_VPN=0
#   ENABLE_HAILO=0

set -euo pipefail

if [[ ${EUID} -ne 0 ]]; then echo "ERROR: usa sudo" >&2; exit 1; fi

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUN_USER="${TRC_USER:-${SUDO_USER:-boss}}"
STATIC_IP="${STATIC_IP:-192.168.50.10}"
SLAVE_IP="${SLAVE_IP:-192.168.50.20}"
TRC_SERVER_URL="${TRC_SERVER_URL:-http://172.30.96.143:8787}"
ETH_IFACE="${ETH_IFACE:-eth0}"
ENABLE_HEARTBEAT="${ENABLE_HEARTBEAT:-1}"
ENABLE_VPN="${ENABLE_VPN:-0}"
ENABLE_HAILO="${ENABLE_HAILO:-0}"
NODE_NAME="${NODE_NAME:-TRC_Urus_master}"

log() { printf "\n=== [%s] %s ===\n" "$(date +%H:%M:%S)" "$*"; }

# ─────────────────────────────────────────────────────── 1. apt deps
log "Phase 1: apt dependencies"
DEBIAN_FRONTEND=noninteractive apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  git git-lfs python3-venv python3-pip python3-dev build-essential \
  iproute2 net-tools curl ca-certificates jq \
  chromium-browser unclutter x11-xserver-utils \
  pipewire pipewire-pulse wireplumber pipewire-audio \
  bluez bluez-tools alsa-utils \
  || true

# ─────────────────────────────────────────────────────── 2. git lfs
log "Phase 2: git lfs pull (DBC/ARXML/FIBEX/PDX/A2L/ODX)"
sudo -u "${RUN_USER}" git -C "${REPO_DIR}" lfs install
sudo -u "${RUN_USER}" git -C "${REPO_DIR}" lfs pull

# ─────────────────────────────────────────────────────── 3. venv
log "Phase 3: Python venv + TRC deps"
sudo -u "${RUN_USER}" python3 -m venv "${REPO_DIR}/.venv"
sudo -u "${RUN_USER}" "${REPO_DIR}/.venv/bin/pip" install --quiet --upgrade pip wheel
sudo -u "${RUN_USER}" "${REPO_DIR}/.venv/bin/pip" install --quiet \
  Flask==3.0.0 'Flask-SocketIO>=5.3,<6' simple-websocket \
  gunicorn 'gevent>=23,<25' gevent-websocket \
  'numpy>=2,<3' asammdf cantools python-can 'can-isotp' \
  'opencv-python-headless<5' scapy \
  'python-socketio[client]>=5.10' 'websocket-client' \
  werkzeug requests

# ─────────────────────────────────────────────────────── 4. Kvaser drivers
log "Phase 4: Kvaser kernel modules (if linuxcan tarball present)"
KVASER_INSTALLER="${REPO_DIR}/kvaser_bus_manager/install/install_kvaser_drivers.sh"
if [[ -x "${KVASER_INSTALLER}" ]] && ! lsmod 2>/dev/null | grep -qE '^(mhydra|leaf|kvpci)'; then
  bash "${KVASER_INSTALLER}" || echo "  WARN: Kvaser install failed (verify USB cable)"
else
  echo "  Kvaser modules already loaded or installer missing — skipping"
fi

# ─────────────────────────────────────────────────────── 5. netplan
log "Phase 5: netplan static IP ${STATIC_IP}/${ETH_IFACE}"
if [[ -d /etc/netplan ]]; then
  cat > /etc/netplan/90-trc-master.yaml <<EOF
# Managed by install_master_turnkey.sh
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    ${ETH_IFACE}:
      addresses:
        - ${STATIC_IP}/24
      dhcp4: false
      dhcp6: false
      optional: true
EOF
  chmod 0600 /etc/netplan/90-trc-master.yaml
fi

# ─────────────────────────────────────────────────────── 6. systemd master service
log "Phase 6: trc-master.service"
TMP_UNIT=$(mktemp)
sed -e "s|__REPO_DIR__|${REPO_DIR}|g" \
    -e "s|__RUN_USER__|${RUN_USER}|g" \
    "${REPO_DIR}/master_node/install/trc-master.service" > "${TMP_UNIT}"
install -m 0644 "${TMP_UNIT}" /etc/systemd/system/trc-master.service
rm -f "${TMP_UNIT}"

cat > /etc/default/trc-master <<EOF
# Generated by install_master_turnkey.sh — modifica e systemctl restart trc-master
TRC_SLAVE_IP=${SLAVE_IP}
TRC_SLAVE_API_PORT=8001
TRC_SLAVE_TOKEN_FILE=/etc/trc-node-token
TRC_NODE_ROLE=master
KBSM_HOST=0.0.0.0
KBSM_PORT=5000
KBSM_TLS=0
TRC_LOG_LEVEL=INFO
EOF
chmod 0644 /etc/default/trc-master

# ─────────────────────────────────────────────────────── 7. trc-heartbeat (opt)
if [[ "${ENABLE_HEARTBEAT}" == "1" ]]; then
  log "Phase 7: TRC heartbeat sender → ${TRC_SERVER_URL}"
  install -d -m 0755 /etc/trc_heartbeat
  if [[ ! -f /etc/trc_heartbeat/config.json ]]; then
    cat > /etc/trc_heartbeat/config.json <<EOF
{
  "trc_server_url": "${TRC_SERVER_URL}",
  "node_name": "${NODE_NAME}",
  "auth_token": "trc-heartbeat-2026",
  "heartbeat_interval_s": 30,
  "vpn_gateway": "${TRC_SERVER_URL##*://}",
  "ping_interval_s": 30
}
EOF
    chmod 0644 /etc/trc_heartbeat/config.json
  fi
  install -m 0755 "${REPO_DIR}/deploy/trc_heartbeat_sender.py" /usr/local/bin/trc_heartbeat_sender.py
  install -m 0644 "${REPO_DIR}/deploy/trc-heartbeat.service" /etc/systemd/system/trc-heartbeat.service
fi

# ─────────────────────────────────────────────────────── 8. autostart display
log "Phase 8: autostart kiosk /display"
DISPLAY_LAUNCH="${REPO_DIR}/kvaser_bus_manager/install/run_kvbm_display.sh"
if [[ -x "${DISPLAY_LAUNCH}" ]]; then
  install -d -o "${RUN_USER}" -g "${RUN_USER}" -m 0755 "/home/${RUN_USER}/.config/autostart"
  cat > "/home/${RUN_USER}/.config/autostart/trc-display.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=TRC Display
Comment=Launch /display fullscreen kiosk
Exec=/bin/sh -c 'KVBM_DISPLAY_URL=http://127.0.0.1:5000/display ${DISPLAY_LAUNCH}'
Terminal=false
X-GNOME-Autostart-enabled=true
X-LXDE-Autostart=true
NoDisplay=false
EOF
  chown "${RUN_USER}:${RUN_USER}" "/home/${RUN_USER}/.config/autostart/trc-display.desktop"
fi

# ─────────────────────────────────────────────────────── 9. (opt) VPN
if [[ "${ENABLE_VPN}" == "1" ]]; then
  log "Phase 9: WireGuard VPN"
  apt-get install -y --no-install-recommends wireguard wireguard-tools
  if [[ ! -f /etc/wireguard/wg-vehicle.conf ]]; then
    install -m 0600 "${REPO_DIR}/deploy/wg-vehicle.conf.example" /etc/wireguard/wg-vehicle.conf
    echo "  WARN: wireguard config is the TEMPLATE — modifica le chiavi prima di abilitare"
  fi
  echo "  attiva con: sudo systemctl enable --now wg-quick@wg-vehicle"
fi

# ─────────────────────────────────────────────────────── 10. (opt) Hailo
if [[ "${ENABLE_HAILO}" == "1" ]]; then
  log "Phase 10: Hailo-8 driver"
  if lspci 2>/dev/null | grep -qi hailo; then
    echo "  Hailo-8 detected"
    echo "  Manual install: https://hailo.ai/developer-zone/sw-downloads/"
  else
    echo "  no Hailo-8 PCIe device detected — skip"
  fi
fi

# ─────────────────────────────────────────────────────── 11. enable + start
log "Phase 11: enable + start services"
systemctl daemon-reload
systemctl enable trc-master.service
systemctl restart trc-master.service
if [[ "${ENABLE_HEARTBEAT}" == "1" ]]; then
  systemctl enable trc-heartbeat.service || true
  systemctl restart trc-heartbeat.service || true
fi
sleep 2
systemctl --no-pager --full status trc-master.service | head -15 || true

cat <<EOF

╔════════════════════════════════════════════════════════════════════╗
║  TRC MASTER turn-key install COMPLETE                              ║
╠════════════════════════════════════════════════════════════════════╣
║  UI:          http://${STATIC_IP}:5000/                            ║
║  Slave panel: http://${STATIC_IP}:5000/slave-node/                 ║
║  Display:     auto-launch (kiosk) al login boss                    ║
║  Heartbeat:   ${ENABLE_HEARTBEAT} → ${TRC_SERVER_URL}              ║
║                                                                    ║
║  Slave config:                                                     ║
║    1. sul Pi slave: sudo bash slave_node/install/install_slave_turnkey.sh
║    2. scp /etc/trc-node-token DAL slave a QUESTO master            ║
║    3. sudo systemctl restart trc-master                            ║
║                                                                    ║
║  Logs:                                                             ║
║    journalctl -u trc-master -f                                     ║
║    journalctl -u trc-heartbeat -f                                  ║
║                                                                    ║
║  Verifica:                                                         ║
║    bash kvaser_bus_manager/install/verify_system.sh                ║
╚════════════════════════════════════════════════════════════════════╝
EOF
